### ISSUE TITLE
Type error: Too many arguments

### ISSUE THREAD

**Issue by dirkonet** [fsr/detach#1]
In line [266](https://github.com/fsr/detach/blob/master/detach.py#L266), `process_mail()` is called with three arguments, but it's only [defined](https://github.com/fsr/detach/blob/master/detach.py#L165) with two arguments, causing an error after selecting a mail to process.

```
found matching mail:
 Subject: FSR Veröffentlichung von [redacted] erfordert Bestätigung
 nested Subject: [redacted]
Process mail? [Y/n]y
Traceback (most recent call last):
 File "detach.py", line 340, in <module>
   run(maildir, conn, exclude_seen, dir_pattern)
 File "detach.py", line 266, in run
   parsed, nested, dir_pattern
TypeError: process_mail() takes 2 positional arguments but 3 were given
```

**Comment by horazont** [comment]
Fixed by actually pushing.
