### ISSUE TITLE
Broken file extension on server

### ISSUE THREAD

**Issue by heisig** [fsr/detach#4]
The recent mail to fsr@ (14.09.2016, 11:58) links to a correct directory but the file extension of the pdf is broken

> Bestellformular akademika 2016.pdf"; size=844052; creation-date="Wed, 14 Sep 2016 09:38:46 GMT"; modification-date="Wed, 14 Sep 2016 09:38:46 GMT

**Comment by mhaehnel** [comment]
This has been broken for quite some time. The parsing is defect (see past mails of the last year or so)

Here is the problematic part:

https://github.com/fsr/detach/blob/master/detach.py#L145-L156

**Comment by mhaehnel** [comment]
The code with all the manual parsing looks pretty crappy. Here is probably how to do it right:

http://stackoverflow.com/questions/4067937/getting-mail-attachment-to-python-file-object

**Comment by horazont** [comment]
Please test #5.
